name: CI
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

#env:
#  NODE_VERSION: 20.11.0

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node version
        run: |
          echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      # TODO This doesn't seem necessary
      - name: Remove .yarnrc file to avoid conflicts
        run: rm -rf .yarnrc

      - name: Enable Corepack
        run: corepack enable

      - name: Prepare and activate Yarn version 1.22.22
        run: corepack prepare yarn@1.22.22 --activate

      - name: Verify Yarn version
        run: yarn --version

      - name: Install dependencies with frozen lockfile
        run: yarn install --frozen-lockfile

      - run: yarn eslint src

  tests:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Setup node version
        run: |
          echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Remove .yarnrc file to avoid conflicts
        run: rm -rf .yarnrc

      - name: Enable Corepack
        run: corepack enable

      - name: Prepare and activate Yarn version 1.22.22
        run: corepack prepare yarn@1.22.22 --activate

      - name: Verify Yarn version
        run: yarn --version

      - name: Install dependencies with frozen lockfile
        run: yarn install --frozen-lockfile

      - name: Running unit tests
        env:
          REACT_APP_API_DOMAIN: http://localhost:8080
        run: yarn test

      # Playwright tests
      - name: Install Playwright dependencies
        run: yarn playwright install
      - name: Running e2e tests
        env:
          PLAYWRIGHT_BASE_URL: https://web-uat.cmiml.net
          PLAYWRIGHT_BASE_URL_API: https://api-uat.cmiml.net
          PLAYWRIGHT_ADMIN_EMAIL: 'automation.test+admin@example.com'
          PLAYWRIGHT_ADMIN_PASSWORD: ${{ secrets.PLAYWRIGHT_ADMIN_PASSWORD }}
          PLAYWRIGHT_AUTOMATION_TEST_USER_EMAIL: 'automation.test+user@example.com'
          PLAYWRIGHT_AUTOMATION_TEST_USER_PASSWORD: ${{ secrets.PLAYWRIGHT_AUTOMATION_TEST_USER_PASSWORD }}
          PLAYWRIGHT_GENERAL_PASSWORD: ${{ secrets.PLAYWRIGHT_GENERAL_PASSWORD }}
        run: |
          yarn test:e2e

  build:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v4
      - name: Setup node version
        run: |
          echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Remove .yarnrc file to avoid conflicts
        run: rm -rf .yarnrc

      - name: Enable Corepack
        run: corepack enable

      - name: Prepare and activate Yarn version 1.22.22
        run: corepack prepare yarn@1.22.22 --activate

      - name: Verify Yarn version
        run: yarn --version


      - name: Install dependencies with frozen lockfile
        run: yarn install --frozen-lockfile

      - name: Build web app
        run: yarn build
