name: CI
on: [pull_request]

#env:
#  NODE_VERSION: 20.11.0

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node version
        run: |
          echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      # TODO This doesn't seem necessary
      - name: Remove .yarnrc file to avoid conflicts
        run: rm -rf .yarnrc

      - name: Enable Corepack
        run: corepack enable

      - name: Prepare and activate Yarn version 1.22.22
        run: corepack prepare yarn@1.22.22 --activate

      - name: Verify Yarn version
        run: yarn --version

      - name: Install dependencies with frozen lockfile
        run: yarn install --frozen-lockfile

      - run: yarn eslint src

  tests:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Setup node version
        run: |
          echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Remove .yarnrc file to avoid conflicts
        run: rm -rf .yarnrc

      - name: Enable Corepack
        run: corepack enable

      - name: Prepare and activate Yarn version 1.22.22
        run: corepack prepare yarn@1.22.22 --activate

      - name: Verify Yarn version
        run: yarn --version

      - name: Install dependencies with frozen lockfile
        run: yarn install --frozen-lockfile

      - name: Running tests
        env:
          REACT_APP_API_DOMAIN: http://localhost:8080
        run: yarn test
  build:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v4
      - name: Setup node version
        run: |
          echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Remove .yarnrc file to avoid conflicts
        run: rm -rf .yarnrc

      - name: Enable Corepack
        run: corepack enable

      - name: Prepare and activate Yarn version 1.22.22
        run: corepack prepare yarn@1.22.22 --activate

      - name: Verify Yarn version
        run: yarn --version


      - name: Install dependencies with frozen lockfile
        run: yarn install --frozen-lockfile

      - name: Build web app
        run: yarn build
