name: CI
on: [pull_request]

env:
  NODE_VERSION: 20.11.0

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: actions/cache@v4
        with:
          path: |
            ~/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Remove .yarnrc file to avoid conflicts
        run: rm -rf .yarnrc
      
      - name: Enable Corepack
        run: corepack enable
      
      - name: Prepare and activate Yarn version 1.22.22
        run: corepack prepare yarn@1.22.22 --activate
      
      - name: Verify Yarn version
        run: yarn --version
      
      - name: Install dependencies with frozen lockfile
        run: yarn install --frozen-lockfile

      - run: yarn eslint src
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Remove .yarnrc file to avoid conflicts
        run: rm -rf .yarnrc
      
      - name: Enable Corepack
        run: corepack enable
      
      - name: Prepare and activate Yarn version 1.22.22
        run: corepack prepare yarn@1.22.22 --activate
      
      - name: Verify Yarn version
        run: yarn --version
      
      - name: Install dependencies with frozen lockfile
        run: yarn install --frozen-lockfile

      - uses: actions/cache@v4
        with:
          path: |
            ~/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Running tests
        env:
          REACT_APP_API_DOMAIN: http://localhost:8080
        run: yarn test
