name: Build and Deploy Dev

on:
  push:
    branches:
      - dev
      - develop

jobs:
  build-deploy:
    name: Build and Deploy
    uses: ./.github/workflows/_build-deploy.yaml
    with:
      env: dev
